language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "jordan-castillo-github"
    token: jordan
      secure: "9038caf6c1304e200f412bc85a8f48ac1c0e891f"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
